version: '3.8'

services:
  public:
    container_name: public_service
    build: public_service
    expose: 
      - "8080"
    ports: 
      - "49160:8080"
    networks:
      - private-network

  
  subscription:
    container_name: subscription_service
    build: subscription_service
    expose: 
      - "8081"
    networks:
      - private-network
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: postgres

  db:
    container_name: db
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    expose:
      - '5432'
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db:
    driver: local

networks:
  private-network:
    driver: bridge